leftnav:
- identifier: c7afa8dc-a12c-73da-bfe2-91544d57c38b
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 74b4d366-8dbf-48ed-fdc4-e9a91a80390b
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 9cad4d7b-1cd6-ef93-84cf-40e5c2bbdb09
  name: Readings and Viewings
  url: /pages/readings-and-viewings
  weight: 30
- identifier: ffa37a46-20f2-af2f-f24a-658af48d155b
  name: Assignments
  url: /pages/assignments
  weight: 40
